### ISSUE TITLE
[medium] Missing label for search form

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-eval-tools#85]
The search form seems to be using `placeholder` rather than a `<label>`. Would it be better with an explicit `<label>` that is visually hidden?

Of course, I could be missing where the label actually is!

**Comment by MicheleAWilliams-A11y** [comment]
Was going to note this as well (and would mark it as "High" priority because it is indeed missing an explicit label). I suggest at least following the WAI guidance on hiding explicit labels (and possibly using the well-known/approved magnifying glass icon in place of the word "Search" if desired): https://www.w3.org/WAI/tutorials/forms/labels/

**Comment by VeraLange** [comment]
The search form now has an explicit label that follows the WAI guidance linked in your reply. Thanks!
