### ISSUE TITLE
[Tool Submission Form] - Calendar/Date picker cannot be opened with keyboard actions

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-eval-tools#95]
You cannot activate the calendar modal with the keyboard, such as in the "Release Date" field.

**Comment by VeraLange** [comment]
Keyboard users can type in the date, and focus on the separate fields (i.e. day, month, year) with tab.

**Comment by MicheleAWilliams-A11y** [comment]
But the calendar should (and can) work too. Otherwise you're not giving equivalent access.

**Comment by VeraLange** [comment]
The date field appears to be a standard component input field of W3C/WAI. We think this issue should be discussed and re-evaluated based on your input for the standard component. We advise against making changes to these fields before a consensus has been reached, so as to prevent inconsistencies across resources. 

@shawna-slh Any thoughts?

**Comment by shawna-slh** [comment]
Hi @VeraLange and @mhansma96
I don't see where the component comes from. I looked at some other date fields and don't see the calendar, e.g., in https://www.w3.org/WAI/eval/report-tool/evaluation/report-findings and https://www.w3.org/WAI/planning/statements/generator/#create
Maybe I'm missing it somewhere?

I think the calendar is not needed for the first iteration. I suggest just removing it for now, and you can leave it for possible future enhancement if it becomes a high enough priority later.

**Comment by VeraLange** [comment]
Hey @shawna-slh and @MicheleAWilliams-A11y 

The date field used is standard as it gets displayed through HTML. 
Removing it or making it a basic text input with rules would mean:
- The tools list can't be sorted by "Most recently updated"  and "Most recently added" 
- Parsing strings to dates can create unforeseen errors, for example by user input mistake
- The standard date field is flexible to the regional settings of a user's browser, so dates will be the same format for this user everywhere

I think we should leave the date field as is for now - since all functionality can still be used, even though the calendar itself can't be accessed by keyboard.

EDIT: as far as we tested it, the calendar can actually be accessed by keyboard: SPACE opens it, and arrow keys control the date picker.

**Comment by shawna-slh** [comment]
If this is using the same date input as https://www.w3.org/WAI/courses/submission/
then I assume it is OK.

Please confirm, then re-close :-)

**Comment by mhansma96** [comment]
Yes, confirmed. It does use the same field!
